version: 2
jobs:
  create-content:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: ls -al workspace
      - run:
          name: Completing the configuration files
          command: bash $PWD/scripts/create-content.sh /tmp/workspace https://github.com/ddvlanck/werkgroep-authtentieke-gegevensbronnen/tree/register
      - run:
          name: Listing all directories and files that have been created
          command: ls -al /tmp/workspace/*
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bronnen/
            - commit.json
  push-to-repository:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Switch to 'website' branch in repository
          command: |
            git checkout website
      - run:
          name: Create content directory if it does not exist
          command: |
            [[ -d content ]] || mkdir content
      - run:
          name: Copying content to website folder 'content'
          command: cp -r /tmp/workspace/bronnen/* content/
      - run:
          name: Insert commit
          command: |
            export TAG=`echo "${CIRCLE_SHA1}"`
            echo "{\"commit\" : \"$TAG\"}" > commit.json
      - run:
          name: Push results to repository on branch 'register'
          command: |
            git config user.email "oslo@oslo"
            git config user.name "Circle CI Builder"
            git add .
            git status
            git commit -m "Applying changes from commit ${CIRCLE_SHA1}" --allow-empty
            export TAG=`echo "${CIRCLE_SHA1}" | cut -c1-15`
            git tag "${TAG}"
            git push --force origin register
workflows:
  version: 2
  create-and-copy-source-content:
    jobs:
      - create-content
      - push-to-repository:
          requires:
            - create-content